
resources:
  repositories:
  - repository: DevOpsTools 
    type: github
    endpoint: Sandbox
    name: wesleycamargo/DevOpsTools

trigger:
- master
- azure-pipelines

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build

    jobs: 
    - job: Build
      steps:
      - checkout: self
      - checkout: DevOpsTools
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '-o $(Build.ArtifactStagingDirectory)'
          modifyOutputPath: false

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'